### PR TITLE
Feat: Added Header Masking

### PR DESCRIPTION
**Pull request by shreyas-londhe**
## Description

This PR introduces header masking. 

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:

- [x] I have discussed with the team prior to submitting this PR
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by saleel — APPROVED** [review]
Looks good to me 🚀

**Comment by saleel** [comment]
Circuit tests are failing here, but passes locally 🤔 
Maybe we reach some limits on Github action containers.

**Comment by shreyas-londhe** [comment]
> Circuit tests are failing here, but passes locally 🤔 Maybe we reach some limits on Github action containers.
It didn't run the tests for my latest commit. I didn't change the workflow file. Do you know what happened?

**Comment by saleel** [comment]
@shreyas-londhe No idea. Try opening another one with same branch. Or maybe add another commit here.

**Comment by shreyas-londhe** [comment]
@saleel @Divide-By-0 please review the changes and merge if everything is good :)

**Pull request merged**
