### PR TITLE
feat: migrate js files to ts

### LINKED ISSUE #131: JS -> TS
`helpers/src/dkim` has a bunch of JS. Replace that with TS.

### PR DESCRIPTION
**Pull request by Dhoni77**
Closes #131

- Migrate js files under helpers/src/dkim to ts
- Add @types to package.json
- Update yarn.lock
- Replace deprecated Buffer's `slice()` with `subarray()`

### CODE REVIEW

**Comment by Dhoni77** [comment]
cc @Divide-By-0

**Comment by Divide-By-0** [comment]
These seem to fail yarn test:e2e-ui

**Comment by Dhoni77** [comment]
> These seem to fail yarn test:e2e-ui @Dhoni77 do you mind fixing that?

Hey @Divide-By-0 how do I run this application in local ?

**Comment by Dhoni77** [comment]
> > > These seem to fail yarn test:e2e-ui @Dhoni77 do you mind fixing that?
> > 
> > 
> > Hey @Divide-By-0 how do I run this application in local ?
> 
> You can do `yarn install` and then `yarn test:e2e-ui`.

Hi @Divide-By-0 For e2e tests, the application must be running right. How do I run the application in local ?

**Comment by Dhoni77** [comment]
> > > These seem to fail yarn test:e2e-ui @Dhoni77 do you mind fixing that?
> > 
> > 
> > Hey @Divide-By-0 how do I run this application in local ?
> 
> You can do `yarn install` and then `yarn test:e2e-ui`.

Hi @Divide-By-0 I am unable to run the tests in local.

**Comment by Divide-By-0** [comment]
> > > > These seem to fail yarn test:e2e-ui @Dhoni77 do you mind fixing that?
> > > 
> > > 
> > > Hey @Divide-By-0 how do I run this application in local ?
> > 
> > 
> > You can do `yarn install` and then `yarn test:e2e-ui`.
> 
> Hi @Divide-By-0 I am unable to run the tests in local.

Can you please send a screenshot or text or something of the errors you get?

**Comment by isidroamv** [comment]
I made this [PR](https://github.com/Dhoni77/zk-email-verify/pull/1). It should solve the error regarding the job `run_unit_and_e2e_tests`

**Comment by Divide-By-0** [comment]
> Hi all, I made this [PR](https://github.com/Dhoni77/zk-email-verify/pull/1). It should solve the error regarding the job `run_unit_and_e2e_tests`

Great,  can you make a PR to the original zkemail repo building atop his PR?

**Pull request merged**
