### PR TITLE
Enhancement: Moved from react to Vite

### PR DESCRIPTION
**Pull request by Ocolus1**

### CODE REVIEW

**Comment by Divide-By-0** [comment]
Your yarn.lock checksum here is wrong:   
`checksum: 03909c769b2fa2c210b0a9ef17c7132824de0aa247626a02864a35d966350e9d2769121e1fab96ce2c81284a956694afb1e2819738e784c889ed6c0fe0d305ab`

Please use 
```
"snarkjs@https://github.com/sampritipanda/snarkjs.git#fef81fc51d17a734637555c6edbd585ecda02d9e":
  version: 0.5.0
  resolution: "snarkjs@https://github.com/sampritipanda/snarkjs.git#commit=fef81fc51d17a734637555c6edbd585ecda02d9e"
  dependencies:
    "@iden3/binfileutils": 0.0.11
    bfj: ^7.0.2
    blake2b-wasm: ^2.4.0
    circom_runtime: 0.1.21
    ejs: ^3.1.6
    fastfile: 0.0.20
    ffjavascript: 0.2.56
    js-sha3: ^0.8.0
    localforage: ^1.10.0
    logplease: ^1.2.15
    r1csfile: 0.0.41
  bin:
    snarkjs: build/cli.cjs
  checksum: f2050f0135d50d459ea0edddf3e394e833a2d28c6648e5889b2f896814865e5c60606e978a8a106bd5bfe7e27501c315f249db5b71895d5e7e6e9a87bfcd55ab
  languageName: node
  linkType: hard
  ```

in your yarn.lock instead to pass tests @Ocolus1

**Comment by Divide-By-0** [comment]
There's still errors: `command not found: react-scripts`.

**Comment by Ocolus1** [comment]
@Divide-By-0 react-scripts was removed intentionally, the test will not pass. It was necessary to convert to Vite.

**Comment by Divide-By-0** [comment]
Try these edits in package.json and test to ensure the scripts work for instance:

```
    "start": "vite",
    "build": "tsc && vite build",
    "serve": "vite preview",
    "both-build": "vite build && next build",
    "next-build": "next build",
    "test": "jest --runInBand --testPathIgnorePatterns='e2e|src/contracts/lib' --reporters=default --reporters=jest-junit",
    "test:browserstack": "browserstack-node-sdk jest src/ --runInBand --testPathIgnorePatterns='e2e|src/contracts/lib' --reporters=default --reporters=jest-junit",
    "start-e2e-test-server": "serve -s build -p 3000",
    "test:e2e-ui": "CI=true jest --runInBand --testPathPattern='e2e-ui' --reporters=default --reporters=jest-junit",
    "test:e2e-zkp": "CI=true jest --runInBand --testPathPattern='e2e-dl-zkp' --reporters=default --reporters=jest-junit",
    "eject": "echo 'The eject command is not available in Vite.'"
```

**Comment by Divide-By-0** [comment]
Closed by https://github.com/zkemail/zk-email-verify/pull/67.

**Pull request closed without merging**
