### PR TITLE
fix: add babel config file to support typescript compilation

### PR DESCRIPTION
**Pull request by isidroamv**
@Metachaser24 I solved the error partially by adding babel.config file into root of the project. Now, I see couple of errors related to some files inside the folder `__fixtures__/`. Do you know the location of these files? are they deprecated?

Fix for https://github.com/zkemail/zk-email-verify/pull/133

### CODE REVIEW

**Comment by Metachaser24** [comment]
No, @isidroamv i dont know about the fixtures directory or any of the files within it.

**Comment by Divide-By-0** [comment]
Yes, that test file is pointing to this file, which you can access in the next 24 hours here:
https://wormhole.app/qPnRd#UAGFbP99yWIh5DHpBTCxuw

**Comment by isidroamv** [comment]
@Metachaser24 @Divide-By-0  I see these files are now distributed in different folders. I believe if put those files at the root of the project we can access to them from any package.

**Comment by Divide-By-0** [comment]
> @Metachaser24 @Divide-By-0 I see these files are now distributed in different folders. I believe if put those files at the root of the project we can access to them from any package.

You're probably right! Feel free to put those at the root.

**Comment by Divide-By-0** [comment]
@isidroamv these tests all pass on main right now. Can you check the discrepancy and help resolve the remaining errors?

**Comment by isidroamv** [comment]
It seems some of the errors are because the `twitter-verifier-*` packages where moved.
https://github.com/zkemail/zk-email-verify/blob/docs/.circleci/config.yml#L64

Screenshot 2023-11-11 at 21 06 37

Screenshot 2023-11-11 at 21 07 39


Also, it looks circom was not was initialized propertly.

Screenshot 2023-11-11 at 21 07 00

**Comment by Divide-By-0** [comment]
> It seems some of the errors are because the `twitter-verifier-*` packages where moved. https://github.com/zkemail/zk-email-verify/blob/docs/.circleci/config.yml#L64
> 
> Screenshot 2023-11-11 at 21 06 37 Screenshot 2023-11-11 at 21 07 39
> Also, it looks circom was not was initialized propertly.
> 
> Screenshot 2023-11-11 at 21 07 00

That's weird, since it's initialized fine in the main branch... what changed in the setup? Can you fix that?

**Comment by Divide-By-0** [comment]
hey @isidroamv do you mind helping us move the twitter circuits into examples/ like they were here in a new branch and moving your fixes over? that way we can unblock merging docs, and your work can be much easier to handle! Plus you can do the migration yourself from scratch, which means you might miss less stuff.

**Comment by isidroamv** [comment]
@Divide-By-0 I can help with that. I was exploring that option yesterday. It will require move those folder out the workspace and update the CI to execute the the e2e test using the new location.

**Comment by Divide-By-0** [comment]
> @Divide-By-0 I can help with that. I was exploring that option yesterday. It will require move those folder out the workspace and update the CI to execute the the e2e test using the new location.

Perfect! Looking forwards to seeing it.

**Pull request closed without merging**
