### PR TITLE
docs: move examples out of the workspace

### PR DESCRIPTION
**Pull request by isidroamv**

### CODE REVIEW

**Comment by isidroamv** [comment]
@Divide-By-0  I believe ` run_forge_tests` is failing because  the env key `ALCHEMY_API_KEY` is not correctly setup. I see the same error in the previous PR. Can you check if the the `ALCHEMY_API_KEY` is okay?

**Comment by Divide-By-0** [comment]
Can you just add this in plaintext as a backup if the alchemy api key is empty 
: GOERLI_ALCHEMY_API_KEY 547924becf984d16b47dbbdaa0dc344d

**Comment by isidroamv** [comment]
I have the same error with the key you provided:

```
Error: 
Could not instantiate forked environment with fork url: https://eth-goerli.g.alchemy.com/v2/547924becf984d16b47dbbdaa0dc344d

Context:
- Error #0: Failed to get latest block number
- Error #1: (code: -32600, message: Must be authenticated!, data: None)
```

Is the key working for you?

**Comment by isidroamv** [comment]
I have a key that works but it is a key that I created from my account in https://www.alchemy.com/dapps/goerli

**Comment by Divide-By-0** [comment]
> I have a key that works but it is a key that I created from my account in https://www.alchemy.com/dapps/goerli. The best practice is setup that key in the CircleCI Dashboard so we avoid putting API_KEY variables in the code

We tried doing that, but external PRs don't get that env vars. I think let's just put your key in there for now.

You can also try: DvukuyBzEK-JyP6zp1NVeNVYLJCrzjp_

**Comment by isidroamv** [comment]
The test cases are passing but it looks the security check didn't pass because the API_KEY is uncovered. It seems possible to configure env vars in the project settings and/or context under organization settings .
@Divide-By-0

**Comment by Divide-By-0** [comment]
> The test cases are passing but it looks the security check didn't pass because the API_KEY is uncovered. It seems possible to configure env vars in the project settings and/or context under organization settings. If you give me access to the circleci project or organization I can figure out how to do it.
> 
> @Divide-By-0

Sure, what messaging platform or email can i send your invite to?

**Comment by isidroamv** [comment]
> > The test cases are passing but it looks the security check didn't pass because the API_KEY is uncovered. It seems possible to configure env vars in the project settings and/or context under organization settings. If you give me access to the circleci project or organization I can figure out how to do it.
> > @Divide-By-0
> 
> Sure, what messaging platform or email can i send your invite to?

I have requested access or you can authorize my current github account.

**Comment by Divide-By-0** [comment]
Hey, I've enabled using env vars on forked PRs. I recommend removing the secret, and it should now just work.

**Comment by isidroamv** [comment]
Tests are passing now.

> Hey, I've enabled using env vars on forked PRs. I recommend removing the secret, and it should now just work. @isidroamv

**Comment by Divide-By-0** [comment]
Can you pre-emptively rebase #143 and #146, so that they don't have to redo their PR in the new location of the moved files?

**Comment by isidroamv** [comment]
I can wait for them to merge their PRs into the main branch in case the have pending changes. So can sync with main with the latest changes.

**Comment by Divide-By-0** [comment]
Can you move all of these changes to https://github.com/zkemail/proof-of-twitter/ and setup that CI? I think ultimately it's better for the examples to be seperate.

**Comment by isidroamv** [comment]
The only problem I see is that we use these examples as e2e test in this repo.

One alternative could be:
1.  Remove e2e testing from this repo and leaving only unit test
2. Add a github action to trigger the e2e execution from using the current branch where it is executed.

If you go with this alternative would be good to remove the e2e from this repo util the new flow is configured.

**Comment by Divide-By-0** [comment]
e2e testing only makes sense in context of the twitter app, right? or do those also check in real-time that changes made to the upstream packages won't break the twitter examples if twitter was to be updated to the latest versions as well (if that's the case then I think we should make twitter a gitmodules of that proof-of-twitter repo, so that new users can fork proof-of-twitter to start building their own apps, but also e2e tests here actually verify new functionality more robustly. I've given you PR access on the proof-of-twitter repo.

**Comment by isidroamv** [comment]
Currently, the twitter-app uses the real-time changes made in the packages and it is being used as an e2e test here.
I believe it is okay to move the examples to the `proof-of-twitter` repo as long we use the the correct branch in the e2e test.

**Comment by saleel** [comment]
@isidroamv Thanks for the PR and the one in proof-of-twitter.
I will merge this `develop` and resolve the conflicts couple of related PRs. We can merge to `main` altogether. Since proof-of-twitter is ready now, I will also remove examples from here.
Tests seems to be fine now, but full e2e tests for twitter is not running in Github Actions now - There is issue created to handle this https://github.com/zkemail/proof-of-twitter/issues/9.

**Comment by saleel** [comment]
Yes, they will be removed. The tests here will be the unit tests for circuit, contract (DKIM registry) and some stuffs in helpers package.
All twitter tests will be in the other repo.

**Pull request merged**
