### PR TITLE
pass LOAD_URL as param, and put LOAD_URL into .env

### PR DESCRIPTION
**Pull request by alvinlee001**

### CODE REVIEW

**Comment by alvinlee001** [comment]
@Divide-By-0 I am not sure if i do it correctly, this is for issue #150

**Comment by alvinlee001** [comment]
Hi @Divide-By-0, am i doing it correctly?

**Comment by saleel** [comment]
Thank you.
I am merging this to develop. There are some related PR, and we are also moving out the twitter example to another repo.
I have made some of the changes you have in #163 without knowing about this PR - I will rebase there.

**Comment by alvinlee001** [comment]
> Thank you. I am merging this to develop. There are some related PR, and we are also moving out the twitter example to another repo - so we can merge to `main` altogether. I have made some of the changes you have in #163 without knowing about this PR - I will rebase there.

Hi @saleel , thanks for merging my code... I was hoping if this count as a contribution and eligible for a bounty? May i know the correct channel to apply for it?

Thanks again.

**Comment by Divide-By-0** [comment]
> > Thank you. I am merging this to develop. There are some related PR, and we are also moving out the twitter example to another repo - so we can merge to `main` altogether. I have made some of the changes you have in #163 without knowing about this PR - I will rebase there.
> 
> Hi @saleel , thanks for merging my code... I was hoping if this count as a contribution and eligible for a bounty? May i know the correct channel to apply for it?
> 
> Thanks again.

Sure, please leave your eth address in the thread!

**Comment by alvinlee001** [comment]
> > > Thank you. I am merging this to develop. There are some related PR, and we are also moving out the twitter example to another repo - so we can merge to `main` altogether. I have made some of the changes you have in #163 without knowing about this PR - I will rebase there.
> > 
> > 
> > Hi @saleel , thanks for merging my code... I was hoping if this count as a contribution and eligible for a bounty? May i know the correct channel to apply for it?
> > Thanks again.
> 
> Sure, please leave your eth address in the thread!

Thanks @Divide-By-0 , my eth address is 0x1c9e88a60c74b519cbfdf589e5b5608553dc65be

**Comment by alvinlee001** [comment]
Hi @Divide-By-0 , any updates?

**Comment by Divide-By-0** [comment]
> Hi @Divide-By-0 , any updates?

Hey, sorry for delay. Will get to it ASAP

**Comment by Divide-By-0** [comment]
@alvinlee001 Sent $50 on Optimism! https://optimistic.ethereum.io/tx/0x81027a1dfe40b992c2036a76efc242d9112176e21531258c4b1332a18f8c7019

**Pull request merged**
